### ISSUE TITLE
NameError: name 'cmdConvertToBam' is not defined

### ISSUE THREAD

**Issue by Shen-Jing** [kamimrcht/ELECTOR#10]
Hello!
Sorry to bother you.

### Error

```python
  File "/mnt/d/tools/ELECTOR/elector/assemblyStats.py", line 183, in computeCoverage
    subprocessLauncher(cmdConvertToBam, outBam)
NameError: name 'cmdConvertToBam' is not defined
```

IMHO, I think variable `mdConvertToBam` (in [assemblyStats.py](https://github.com/kamimrcht/ELECTOR/blob/master/elector/assemblyStats.py#L177) line 177) is just a typo?

Thank you.

**Comment by morispi** [comment]
Hi,

Thanks for bringing up this issue.
Indeed, variable was a typo.
Fixed it now.

Best,
Pierre
