### ISSUE TITLE
Maybe function `loadReference` inaccurately works?

### ISSUE THREAD

**Issue by Shen-Jing** [kamimrcht/ELECTOR#11]
Hello,
Sorry to bother you.

These sequences in this [Yeast FASTA file](https://github.com/kamimrcht/ELECTOR/blob/master/reproduce_manuscript_results/references/Yeast.fasta) are separated by newline, 
not like `Ecoli.fasta` (header & the corresponding sequence are 2 lines as one pair/chromosome).

After [function](https://github.com/kamimrcht/ELECTOR/blob/master/elector/readAndSortFiles.py#L299) `loadReference` parsed, `fSeqs` will be:

![2021-04-08_14-41-20](https://user-images.githubusercontent.com/9480153/113986373-c519c100-987f-11eb-958f-a7f73a3fec43.png)

And I got this error: 

```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/shenjing/ELECTOR/elector/__main__.py", line 167, in <module>
    main()
  File "/home/shenjing/ELECTOR/elector/__main__.py", line 121, in main
    clipsNb = readAndSortFiles.processReadsForAlignment(soft, reference, uncorrected, corrected, size, split, simulator, dazzDb, outputDirPath)
  File "/home/shenjing/ELECTOR/elector/readAndSortFiles.py", line 471, in processReadsForAlignment
    convertSimulationOutputToRefFile(uncorrected, reference, simulator, outputDirPath)
  File "/home/shenjing/ELECTOR/elector/readAndSortFiles.py", line 459, in convertSimulationOutputToRefFile
    generateRefReadsSimLord(simulatedPrefix + ".sam", referenceGenome, outputDirPath + "/" + basename(simulatedPrefix) + "_reference.fasta")
  File "/home/shenjing/ELECTOR/elector/readAndSortFiles.py", line 365, in generateRefReadsSimLord
    seq = fSeqs[refId][pos:pos+len]
KeyError: 'scf7180000000104|quiver'
```

IMHO, it seems wrongly parse the reference file?

### My try

We use `awk` to preprocessing `Yeast.fasta`:
```bash
awk '{if($1 ~ /^>/ )print("\n"$0); if($1 !~ /^>/)printf($0)}' Yeast_old.fasta | tail -n +2 > Yeast_new.fasta
```

BTW, thanks my friend @Dada870423 for supporting this script!

And this time, `fSeqs` was successfully set (and no same error):

![2021-04-08_15-31-15](https://user-images.githubusercontent.com/9480153/113986672-13c75b00-9880-11eb-9232-87636648f1ee.png)

Thank you.

**Comment by morispi** [comment]
Hello,

Yes, the loading of the reference sequences currently only supports genomes that are in "one sequence per line" format, as mentioned in the README (referenceGenome.fa is the reference genome, with one sequence per line). This can indeed be quite a limitation, so I will be taking a look at this and allow sequences to span on multiple lines this morning. I will keep you updated when this is solved.

Best,
Pierre

**Comment by morispi** [comment]
Just pushed a fix that should solve this issue as well. Can you pull and tell me if this works for you?

**Comment by Shen-Jing** [comment]
Hi Pierre,

> only supports genomes that are in "one sequence per line" format, as mentioned in the README

Oops, sorry I missed it.

Now it works for me, thanks your fix!

Jing
