### ISSUE TITLE
ValueError: too many values to unpack (expected 5) in `assemblyStats.generateResults`

### ISSUE THREAD

**Issue by Shen-Jing** [kamimrcht/ELECTOR#14]
Hello,
Sorry to bother you.

There are **6** returning values in [assemblyStats.generateResults](https://github.com/kamimrcht/ELECTOR/blob/master/elector/assemblyStats.py#L198).

But in [main](https://github.com/kamimrcht/ELECTOR/blob/master/elector/__main__.py#L159) function, there are only ***5*** variables corresponding to these returning values.

I have fixed it and created a pull request #13.
If there is no problem, could you merge it? I hope it didn't offend you.

Thank you. 😺

**Comment by morispi** [comment]
Hello,

You're not bothering us, no need to apologize. :)

Thanks a lot for spotting and patching this error!
No offence taken, don't worry. It's actually greatly appreciated that you took some of your time to fix our tool.

I will be merging your PR and taking a look at your other issues a bit later today. Sorry for taking so long to answer, but the last few days have been quite busy.

Best,
Pierre

**Comment by morispi** [comment]
Closing the issue, since the PR has been merged. Taking a look at others issues.

**Comment by Shen-Jing** [comment]
Hello Pierre,

Thank you so much for your response & merging! 🤗


Jing
