### ISSUE TITLE
Contigs are not be generated when another tool is used (and its corrected reads are split).

### ISSUE THREAD

**Issue by Shen-Jing** [kamimrcht/ELECTOR#15]
Hello!

When I used another tool which is not in the [list](https://github.com/kamimrcht/ELECTOR#current-compatible-correctors).

I got this error when elector was in the "assembly" stage:

```python
Traceback (most recent call last):
  File "/home/shenjing/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shenjing/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/d/tools/ELECTOR/elector/__main__.py", line 167, in <module>
    main()
  File "/mnt/d/tools/ELECTOR/elector/__main__.py", line 159, in main
    nbContigs, nbAlContig, nbBreakpoints, NG50, NG75, cov = assemblyStats.generateResults(corrected, reference, args.threads, logFile)
  File "/mnt/d/tools/ELECTOR/elector/assemblyStats.py", line 210, in generateResults
    computeIdentity(readsBaseName + ".contigs.sam", readsBaseName + ".contigs.id")
  File "/mnt/d/tools/ELECTOR/elector/assemblyStats.py", line 90, in computeIdentity
    while line[0] == "@":
IndexError: string index out of range
```

After I researched it, I found the input of `miniasm` have reads with same names.
And then it resulted in this error. ([miniasm #24](https://github.com/lh3/miniasm/issues/24))

### My additional parameter

```bash
-split -remap -assemble -simulator simlord
```

I'm sure I didn't use the -corrector parameter.

### My attempt

This time I renamed the corrected reads (add `_0`, `_1`... at the header end) and replaced the original file when ELECTOR entering assembly stage.
And no problem occurred.

Second time I used the renamed file (split reads which have suffix id) as ELECTOR input (corrected reads), I got this error:

```python
- Means that a large amount of reads has been handled: 10000
/mnt/d/tools/ELECTOR/elector/../bin/masterSplitter /mnt/d/Data/Ecoli/Ecoli_d20_Kevin/reference_sorted_duplicated.fa /mnt/d/Data/Ecoli/Ecoli_d20_Kevin/uncorrected_sorted_duplicated.fa /mnt/d/Data/Ecoli/Ecoli_d20_Kevin/corrected_sorted.f
a /mnt/d/Data/Ecoli/Ecoli_d20_Kevin/out1 /mnt/d/Data/Ecoli/Ecoli_d20_Kevin/out2 /mnt/d/Data/Ecoli/Ecoli_d20_Kevin/out3 7 200 10000 0.1 /mnt/d/Data/Ecoli/Ecoli_d20_Kevin
10000 200 50
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------rm: cannot remove '/mnt/d/Data/Ecoli/Ecoli_d20_Kevin/smsa*': No such file or directory
None
grep: /mnt/d/Data/Ecoli/Ecoli_d20_Kevin/msa.fa: No such file or directory
Traceback (most recent call last):
  File "/home/shenjing/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shenjing/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/d/tools/ELECTOR/elector/__main__.py", line 167, in <module>
    main()
  File "/mnt/d/tools/ELECTOR/elector/__main__.py", line 141, in main
    nbReads, throughput, precision, recall, correctBaseRate, errorRate, smallReads, wronglyCorReads, percentGCRef, percentGCCorr, numberSplit, meanMissing, numberExtended, meanExtension, minLength, indelsubsUncorr, indelsubsCorr , trun
cated, ratioHomopolymer = computeStats.outputRecallPrecision(sortedCorrectedFileName, outputDirPath, logFile, smallReads, wronglyCorReads, reportedHomopolThreshold, size_corrected_read_threshold, readSizeDistribution, clipsNb, 0, 0, so
ft)
  File "/mnt/d/tools/ELECTOR/elector/computeStats.py", line 210, in outputRecallPrecision
    nbReads, throughput, uncorThroughput, precision, recall, corBasesRate, errorRate, uncorCorBasesRate, uncorErrorRate, missingSize,  GCRateRef, GCRateCorr,  indelsubsUncorr, indelsubsCorr,  ratioHomopolymers, lenAllCorrectedReads,  c
ountReadSplit, countReadTrimmed, countReadExtended, extendedBasesCount  = computeMetrics(outDir + "/msa.fa", outMetrics, correctedFileName, reportedHomopolThreshold, clipsNb, readsToSplit)
  File "/mnt/d/tools/ELECTOR/elector/computeStats.py", line 520, in computeMetrics
    msa = open(fileName, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/Data/Ecoli/Ecoli_d20_Kevin/msa.fa'
```

IMHO, Maybe something went wrong in the pre-processing stage?

Thank you.

Jing

**Comment by morispi** [comment]
Hello,

Sorry for getting back to you so late, last weeks have been pretty busy.

Renaming the corrected reads by adding `_0` `_1` etc was indeed the correct way to deal with this miniasm problem!

For the last part of your question
> Second time I used the renamed file (split reads which have suffix id) as ELECTOR input (corrected reads), I got this error:

This might be caused by the fact you didn't use the `-corrector` parameter. By default, when this is not provided, ELECTOR will assume reads are not tagged with `_0` `_1` suffixes.
Re-running experiments providing, for instance `-corrector lordec` and `-split` should fix the issue, since this suffix thing is how lordec tags its split reads.

Thank you for pointing out this issue. I will work on fixing this so everything works correctly when the `-corrector` parameter is not provided.

Can you tell me if you manage to get working using the solution I provided, before I work on the proper fix?

Best,
Pierre

**Comment by Shen-Jing** [comment]
Hello, Pierre

> Re-running experiments providing, for instance -corrector lordec and -split should fix the issue, since this suffix thing is how lordec tags its split reads.
> Can you tell me if you manage to get working using the solution I provided, before I work on the proper fix?

Yes, it works!

Thank you.

Jing

**Comment by morispi** [comment]
Great! Gonna try to update the code later today so that providing `-corrector lordec` isn't necessary anymore.

**Comment by morispi** [comment]
Latest commit shall fix this issue.

Cheers,
Pierre
