### ISSUE TITLE
Maybe function `generateRefReadsNanosim` inaccurately works?

### ISSUE THREAD

**Issue by Shen-Jing** [kamimrcht/ELECTOR#16]
Hello, 

- NanoSim Version: 3.0.0

#### NanoSim command

```bash
./src/read_analysis.py genome -i ecoli_R7_2D.fasta -rg ecoli_K12_MG1655_ref.fa -o ecoli

./src/simulator.py genome -dna_type circular -rg ecoli_K12_MG1655_ref.fa -c ecoli
```

And I got this error when using `-simulator nanosim`:

```python
Traceback (most recent call last):
  File "/home/shenjing/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shenjing/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/d/tools/ELECTOR/elector/__main__.py", line 167, in <module>
    main()
  File "/mnt/d/tools/ELECTOR/elector/__main__.py", line 121, in main
    clipsNb = readAndSortFiles.processReadsForAlignment(soft, reference, uncorrected, corrected, size, split, simulator, dazzDb, outputDirPath)
  File "/mnt/d/tools/ELECTOR/elector/readAndSortFiles.py", line 466, in processReadsForAlignment
    convertSimulationOutputToRefFile(uncorrected, reference, simulator, outputDirPath)
  File "/mnt/d/tools/ELECTOR/elector/readAndSortFiles.py", line 448, in convertSimulationOutputToRefFile
    generateRefReadsNanosim(simulatedPrefix + "_reads.fasta", referenceGenome, outputDirPath + "/" + basename(simulatedPrefix) + "_reference.fasta")
  File "/mnt/d/tools/ELECTOR/elector/readAndSortFiles.py", line 323, in generateRefReadsNanosim
    pos = int(id[1])
ValueError: invalid literal for int() with base 10: '4321592;aligned'
```

And this are my breakpoint and watched variables:
![image](https://user-images.githubusercontent.com/9480153/119785088-755f8980-bf01-11eb-87d2-34b4c9699189.png)

IMHO, it seems wrongly parse header name?

Thank you.

Jing

**Comment by morispi** [comment]
Hello,

We used NanoSim v1.0.0 when developing ELECTOR, so this might be due to the fact NanoSim changed the way it generates it's header. Could you please provide me with the first few headers of your reads so I can properly work on the issue?

Thanks,
Pierre

**Comment by Shen-Jing** [comment]
Hello, 

> Could you please provide me with the first few headers of your reads so I can properly work on the issue?

After this:
```bash
./src/simulator.py genome -dna_type circular -rg ecoli_K12_MG1655_ref.fa -c ecoli
```

It generated 2 files:
- simulated_aligned_reads.fasta
- simulated_unaligned_reads.fasta

And these are some of `cat` results (header only):
```
>ENA|U00096|U00096_4321592;aligned_0_F_950_11175_163
>ENA|U00096|U00096_624719;aligned_1_F_123_9209_592
...(removed)
>ENA|U00096|U00096_4337771;aligned_14832_R_28_2350_6
>ENA|U00096|U00096_3651742_unaligned_14833_R_0_2255_0
...(removed)
>ENA|U00096|U00096_1537553_unaligned_19998_R_0_2384_0
>ENA|U00096|U00096_1764050_unaligned_19999_R_0_9607_0
```

Thank you very much.

Jing

**Comment by morispi** [comment]
Can't be 100% sure, but I would believe this is because aligned reads contain a ; where unaligned reads contain a _ in the headers. In the data we used to test ELECTOR on NanoSim data, all reads had a _ whether they were aligned or not. Moreover, we only had a single output file, with both aligned and unaligned reads mixed up.

I thaink that replacing ; with _ e.g. with `sed 's/;/_/g'` could probably fix the issue. Could you try out and tell me if this works? Sorry if this is not super practical, but it's hard to keep things up to date when tools change the way they name the reads from one version to another.

Pierre

**Comment by Shen-Jing** [comment]
Hello,
> `sed 's/;/_/g'`
> Could you try out and tell me if this works?

Yes, it works!
It is a clever idea!

> ...but it's hard to keep things up to date when tools change the way they name the reads from one version to another.

I'm with you on that.

Thank you very much for helping me.

Jing
