### ISSUE TITLE
Support for latest version of SimLoRD?

### ISSUE THREAD

**Issue by Shen-Jing** [kamimrcht/ELECTOR#6]
Hello,
When I running this [script (reproduce_manuscript_results)](https://github.com/kamimrcht/ELECTOR/blob/master/reproduce_manuscript_results/longReads/simEcoli.sh),
I got these errors:
```shell
simlord --read-reference ../references/Ecoli.fasta -t 0.305 -pi 0.22 -pd 0.08 -ps 0.01 --coverage 20 --sam-output simEcoli.sam simEcoli
Time for reading/generating the reference: 0:00:00.042872 h
Traceback (most recent call last):
  File "/home/shenjing/anaconda3/envs/simlord/bin/simlord", line 8, in <module>
    sys.exit(main())
  File "/home/shenjing/anaconda3/envs/simlord/lib/python3.8/site-packages/simlord/simlord.py", line 866, in main
    simulate(args)
  File "/home/shenjing/anaconda3/envs/simlord/lib/python3.8/site-packages/simlord/simlord.py", line 838, in simulate
    sample_reads(reference=reference, num_reads=num_reads,
  File "/home/shenjing/anaconda3/envs/simlord/lib/python3.8/site-packages/simlord/simlord.py", line 299, in sample_reads
    write_sam_file(sam_writer, name, read, quality_values.encode(), reversals[i],
  File "/home/shenjing/anaconda3/envs/simlord/lib/python3.8/site-packages/simlord/simlord.py", line 519, in write_sam_file
    a.query_name = name
  File "pysam/libcalignedsegment.pyx", line 1175, in pysam.libcalignedsegment.AlignedSegment.query_name.__set__
ValueError: query length out of range 252 > 251
```

SimLoRD has been updated to version 1.0.4 (2020-01-07).
And [the latest commit](https://github.com/kamimrcht/ELECTOR/commit/771b24d3ed4971f564d6825d836ea6a726b14e42) of ELECTOR is on 2019-09.

It seems this `simlord` command are not compatible with the latest SimLord?

Thank you!

**Comment by morispi** [comment]
Hello,

This actually sounds like an error with SimLord itself, not with ELECTOR.
I just installed the latest version of SimLord and got the same error when attempting to simulate reads.

After a bit of research, the error seems to happen when using the `--coverage` option. When using this option, specifying anything else than `--coverage 1` results in the error you mentioned (ValueError: query length out of range 252 > 251).

For some reasons, this seems to be related to the header of the reference genome (the line starting with a ">"). Changing this header to some other, random header, like so : `sed -i s'/>.*/>ARandomHeader/g' references/Ecoli.fasta`, weirdly seems to fix the issue.

The issue does not seem to happen with other provided reference genomes, A. baylyi and S. cerevisiae. `--coverage` can be freely used on those genome, with any value, and does not cause any problem.

Super weird. This is probably related to some character in the header, but I am not sure which one for now. I will investigate some more. Keep me updated if changing the header from E. coli did not help.

Cheers,
Pierre

**Comment by Shen-Jing** [comment]
Hello,

Thanks for your reply. 😄

> For some reasons, this seems to be related to the header of the reference genome (the line starting with a ">"). Changing this header to some other, random header, like so : `sed -i s'/>.*/>ARandomHeader/g' references/Ecoli.fasta`, weirdly seems to fix the issue.
> 
> The issue does not seem to happen with other provided reference genomes, A. baylyi and S. cerevisiae. `--coverage` can be freely used on those genome, with any value, and does not cause any problem.

I never thought this error is related to header.
You’re really something!

Thanks your solution.
And I made some attempts at header name:

`>NC_000913.3 Escherichia coli str. K-12 substr. MG1655, complete genome` (original: 70 characters)
→
`>okokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokokok`

Or `Yeast.fasta`
`>scf7180000000084|quiver`
→
`>scf7180000000084|quiverscf7180000000084|quiverscf7180000000084|quiverr` (equal to 70 characters)

These 2 cases got same error.
Maybe this error is also related to header length?

Thank you!
